/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CoolRouteImport } from './routes/cool'
import { Route as IndexRouteImport } from './routes/index'

const CoolRoute = CoolRouteImport.update({
  id: '/cool',
  path: '/cool',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cool': typeof CoolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cool': typeof CoolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cool': typeof CoolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cool'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cool'
  id: '__root__' | '/' | '/cool'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CoolRoute: typeof CoolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/cool': {
      id: '/cool'
      path: '/cool'
      fullPath: '/cool'
      preLoaderRoute: typeof CoolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CoolRoute: CoolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
